"""Added updated_price to PriceAlert

Revision ID: 5fd76c4afc69
Revises: 54f71ae6615b
Create Date: 2025-04-01 22:34:29.371653

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5fd76c4afc69'
down_revision = '54f71ae6615b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_alert', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_on', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_price', sa.Float(), nullable=True))
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_alert', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('updated_price')
        batch_op.drop_column('created_on')

    # ### end Alembic commands ###
